### ISSUE TITLE
Sponsors in the footer

### ISSUE THREAD

**Issue by cexbrayat** [mix-it/linkit#234]
Pointed out by @dgageot 

https://twitter.com/dgageot/status/445576655730667520

**Comment by mpetitdant** [comment]
Do we close this one or do we think something can be done ?

**Comment by clacote** [comment]
I would like to forget everything about this bug, like it never happened.

**Comment by mpetitdant** [comment]
Let's do that !

**Comment by mpetitdant** [comment]
Serli is not a sponsor this year, issue solved !
