### ISSUE TITLE
Home : link to previous sessions on all previous events (mixit13, mixit12, ...).

### ISSUE THREAD

**Issue by clacote** [mix-it/linkit#279]

**Comment by mpetitdant** [comment]
How did you see that ? One line per event ?

**Comment by clacote** [comment]
Yes. But I don't see it very useful now. There are visible in "Infos / Mix-IT 201x" menu (http://www.mix-it.fr/infos/mixit14, http://www.mix-it.fr/infos/mixit13)

**Comment by mpetitdant** [comment]
So it's a go for closing the issue ?

**Comment by clacote** [comment]
Yeah! \o/
No more issues!
