### ISSUE TITLE
Speaker preferences : datetimepicker

### ISSUE THREAD

**Issue by clacote** [mix-it/linkit#362]
A datetime picker would have been nice. Currently, there is a "required pattern" displayed, but you can type anything in input field without error. Hiding the "required" hint would be a minimum if there is no required pattern and datetimepicker.

**Comment by clacote** [comment]
cc @mpetitdant

**Comment by mpetitdant** [comment]
So I'm changing the pattern as an example, I open the dashboard link and we can make it test to the speaker that answered with constraints.
