### ISSUE TITLE
API: custom serializer `MemberJsonSerializer` is not used anymore

### ISSUE THREAD

**Issue by clacote** [mix-it/linkit#391]
http://www.mix-it.fr/api/members/staff and http://www.mix-it.fr/api/members/staff?details=true produce same JSON result, from default Member entity serialization, not the one produced by `MemberJsonSerializer`.

**Comment by clacote** [comment]
Serialization should be revamped totally, as our Gson usage of custom serializers is obviously not mastered. Maybe we should use a manual marshalling though Jackson. Or serialize POJO/DTO, where the default serialization should be enough.

**Comment by javamind** [comment]
With the last modification we have this result
![image](https://cloud.githubusercontent.com/assets/1812822/6848633/a7da00b8-d3ce-11e4-95af-be1992f8ac5b.png)

Can I repush my branch which is not made with the Play standard. The result is below
![image](https://cloud.githubusercontent.com/assets/1812822/6848670/e6d53760-d3ce-11e4-8660-89c69f9e22d1.png)

**Comment by clacote** [comment]
You're always free to make PR.
