### ISSUE TITLE
Problem on API

### ISSUE THREAD

**Issue by javamind** [mix-it/linkit#403]
We don't know if a session is a talk, a keynote or a workshp

**Comment by javamind** [comment]
the session is level is lost

**Comment by javamind** [comment]
Can we filter the active members ? The size is too high ==> 10Mo

**Comment by clacote** [comment]
I'll deal with the missing data tomorrow morning.
Regarding filtering "active" member, that could be done by querying activities, but it's always tricky to define a good window restriction. We're a big conference, that's the price to pay! :).
But I'm happy that this refactoring didn't blow up with extra-memory consumption.
